name: chatview
description: A Flutter package that allows you to integrate Chat View with highly customization options.
version: 2.5.0
issue_tracker: https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues
repository: https://github.com/SimformSolutionsPvtLtd/flutter_chatview

platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux:

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  audio_waveforms: ^1.3.0
  cached_network_image: ^3.4.1
  chatview_utils: ^0.0.1
  intl: ^0.20.2
  url_launcher: ^6.3.1
  emoji_picker_flutter: ^4.3.0
  any_link_preview: ^3.0.3
  image_picker: ^1.1.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

